# PostgreSQL configuration
# Make sure you have PostgreSQL installed and running.
# You can install it locally or run it with Docker.
#   gem install pg
#
#   Ensure the PostgreSQL gem is defined in your Gemfile:
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: db
  port: 5432
  pool: 5

development:
  <<: *default
  database: ferremateriales_development

test:
  <<: *default
  database: ferremateriales_test

production:
  <<: *default
  database: ferremateriales_production
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "password" %>
  host: <%= ENV["POSTGRES_HOST"] || "db" %>
